djangobb_forum/urls.py
from django.conf.urls.defaults import *

from djangobb_forum import settings as forum_settings
from djangobb_forum import views as forum_views
from djangobb_forum.feeds import LastPosts, LastTopics, LastPostsOnForum, \
     LastPostsOnCategory, LastPostsOnTopic
from djangobb_forum.forms import EssentialsProfileForm, \
    PersonalProfileForm, MessagingProfileForm, PersonalityProfileForm, \
    DisplayProfileForm, PrivacyProfileForm, UploadAvatarForm


urlpatterns = patterns('',

    # Forum
    url('^$', forum_views.index, name='index'),
    url('^(?P<forum_id>\d+)/$', forum_views.show_forum, name='forum'),
    url('^moderate/(?P<forum_id>\d+)/$', forum_views.moderate, name='moderate'),
    url('^search/$', forum_views.search, name='search'),
    url('^misc/$', forum_views.misc, name='misc'),

    # User
    url('^user/(?P<username>.*)/upload_avatar/$', forum_views.upload_avatar, {
        'form_class': UploadAvatarForm,
        'template': 'djangobb_forum/upload_avatar.html'
        }, name='forum_profile_upload_avatar'),
    url('^user/(?P<username>.*)/privacy/$', forum_views.user, {
        'section': 'privacy',
        'form_class': PrivacyProfileForm,
        'template': 'djangobb_forum/profile/profile_privacy.html'
        }, name='forum_profile_privacy'),
    url('^user/(?P<username>.*)/display/$', forum_views.user, {
        'section': 'display',
        'form_class': DisplayProfileForm,
        'template': 'djangobb_forum/profile/profile_display.html'
        }, name='forum_profile_display'),
    url('^user/(?P<username>.*)/personality/$', forum_views.user, {
        'section': 'personality',
        'form_class': PersonalityProfileForm,
        'template': 'djangobb_forum/profile/profile_personality.html'
        }, name='forum_profile_personality'),
    url('^user/(?P<username>.*)/messaging/$', forum_views.user, {
        'section': 'messaging',
        'form_class': MessagingProfileForm,
        'template': 'djangobb_forum/profile/profile_messaging.html'
        }, name='forum_profile_messaging'),
    url('^user/(?P<username>.*)/personal/$', forum_views.user, {
        'section': 'personal',
        'form_class': PersonalProfileForm,
        'template': 'djangobb_forum/profile/profile_personal.html'
        }, name='forum_profile_personal'),
    url('^user/(?P<username>.*)/essentials/$', forum_views.user, name='forum_profile_essentials'),
    url('^user/(?P<username>.*)/$', forum_views.user, name='forum_profile'),
    url('^users/$', forum_views.users, name='forum_users'),

    # Topic
    url('^topic/(?P<topic_id>\d+)/$', forum_views.show_topic, name='topic'),
    url('^(?P<forum_id>\d+)/topic/add/$', forum_views.add_topic, name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/delete_posts/$', forum_views.delete_posts, name='delete_posts'),
    url('^topic/move/$', forum_views.move_topic, name='move_topic'),
    url('^topic/(?P<topic_id>\d+)/stick_unstick/(?P<action>[s|u])/$', forum_views.stick_unstick_topic, name='stick_unstick_topic'),
    url('^topic/(?P<topic_id>\d+)/open_close/(?P<action>[c|o])/$', forum_views.open_close_topic, name='open_close_topic'),

    # Post
    url('^post/(?P<post_id>\d+)/$', forum_views.show_post, name='post'),
    url('^post/(?P<post_id>\d+)/edit/$', forum_views.edit_post, name='edit_post'),
    url('^post/(?P<post_id>\d+)/delete/$', forum_views.delete_post, name='delete_post'),
    # Post preview
    url(r'^preview/$', forum_views.post_preview, name='post_preview'),

    # Subscription
    url('^subscription/topic/(?P<topic_id>\d+)/delete/$', forum_views.delete_subscription, name='forum_delete_subscription'),
    url('^subscription/topic/(?P<topic_id>\d+)/add/$', forum_views.add_subscription, name='forum_add_subscription'),

    # Feeds
    url(r'^feeds/posts/$', LastPosts(), name='forum_posts_feed'),
    url(r'^feeds/topics/$', LastTopics(), name='forum_topics_feed'),
    url(r'^feeds/topic/(?P<topic_id>\d+)/$', LastPostsOnTopic(), name='forum_topic_feed'),
    url(r'^feeds/forum/(?P<forum_id>\d+)/$', LastPostsOnForum(), name='forum_forum_feed'),
    url(r'^feeds/category/(?P<category_id>\d+)/$', LastPostsOnCategory(), name='forum_category_feed'),
)

### EXTENSIONS ###

# LOFI Extension
if (forum_settings.LOFI_SUPPORT):
    urlpatterns += patterns('',
        url('^lofi/$', forum_views.index, {'full':False}, name='lofi_index'),
        url('^(?P<forum_id>\d+)/lofi/$', forum_views.show_forum, {'full':False}, name='lofi_forum'),
        url('^topic/(?P<topic_id>\d+)/lofi/$', forum_views.show_topic, {'full':False}, name='lofi_topic'),
    )

# REPUTATION Extension
if (forum_settings.REPUTATION_SUPPORT):
    urlpatterns += patterns('',
        url('^reputation/(?P<username>.*)/$', forum_views.reputation, name='reputation'),
    )

# ATTACHMENT Extension
if (forum_settings.ATTACHMENT_SUPPORT):
    urlpatterns += patterns('',
        url('^attachment/(?P<hash>\w+)/$', forum_views.show_attachment, name='forum_attachment'),
    )

project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from djangobb_forum import settings as forum_settings
from project.sitemap import SitemapForum, SitemapTopic

admin.autodiscover()

sitemaps = {
    'forum': SitemapForum,
    'topic': SitemapTopic,
}

urlpatterns = patterns('',
    # auto redirect to /form/
    url(r'^$', RedirectView.as_view(url='/forum/')),
    
    url(r'^forum/account/', include('django_authopenid.urls')),
    url(r'^forum/', include('djangobb_forum.urls', namespace='djangobb')),
    
    # Sitemap
    (r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    
    url(r'^admin/', include(admin.site.urls)),
)

# PM Extension
if forum_settings.PM_SUPPORT:
    urlpatterns += patterns('',
        (r'^forum/pm/', include('django_messages.urls')),
   )

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'),
            'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

djangobb_forum/views.py
# coding: utf-8

import math
from datetime import timedelta
from django.utils import timezone

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.core.cache import cache
from django.core.exceptions import SuspiciousOperation
from django.core.urlresolvers import reverse
from django.db import transaction
from django.db.models import Q, F
from django.http import Http404, HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import get_object_or_404, render
from django.utils.encoding import smart_str
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_exempt

from haystack.query import SearchQuerySet, SQ

from djangobb_forum import settings as forum_settings
from djangobb_forum.forms import AddPostForm, EditPostForm, UserSearchForm, \
    PostSearchForm, ReputationForm, MailToForm, EssentialsProfileForm, \
    VotePollForm, ReportForm, VotePollForm, PollForm
from djangobb_forum.models import Category, Forum, Topic, Post, Reputation, \
    Attachment, PostTracking
from djangobb_forum.templatetags import forum_extras
from djangobb_forum.templatetags.forum_extras import forum_moderated_by
from djangobb_forum.util import build_form, paginate, set_language, smiles, convert_text_to_html




def index(request, full=True):
    users_cached = cache.get('djangobb_users_online', {})
    users_online = users_cached and User.objects.filter(id__in=users_cached.keys()) or []
    guests_cached = cache.get('djangobb_guests_online', {})
    guest_count = len(guests_cached)
    users_count = len(users_online)

    _forums = Forum.objects.all()
    user = request.user
    if not user.is_superuser:
        user_groups = user.groups.all() or [] # need 'or []' for anonymous user otherwise: 'EmptyManager' object is not iterable
        _forums = _forums.filter(Q(category__groups__in=user_groups) | Q(category__groups__isnull=True))

    _forums = _forums.select_related('last_post__topic', 'last_post__user', 'category')

    cats = {}
    forums = {}
    for forum in _forums:
        cat = cats.setdefault(forum.category.id,
            {'id': forum.category.id, 'cat': forum.category, 'forums': []})
        cat['forums'].append(forum)
        forums[forum.id] = forum

    cmpdef = lambda a, b: cmp(a['cat'].position, b['cat'].position)
    cats = sorted(cats.values(), cmpdef)

    to_return = {'cats': cats,
                'posts': Post.objects.count(),
                'topics': Topic.objects.count(),
                'users': User.objects.count(),
                'users_online': users_online,
                'online_count': users_count,
                'guest_count': guest_count,
                'last_user': User.objects.latest('date_joined'),
                }
    if full:
        return render(request, 'djangobb_forum/index.html', to_return)
    else:
        return render(request, 'djangobb_forum/lofi/index.html', to_return)


@transaction.commit_on_success
def moderate(request, forum_id):
    forum = get_object_or_404(Forum, pk=forum_id)
    topics = forum.topics.order_by('-sticky', '-updated').select_related()
    if request.user.is_superuser or request.user in forum.moderators.all():
        topic_ids = request.POST.getlist('topic_id')
        if 'move_topics' in request.POST:
            return render(request, 'djangobb_forum/move_topic.html', {
                'categories': Category.objects.all(),
                'topic_ids': topic_ids,
                'exclude_forum': forum,
            })
        elif 'delete_topics' in request.POST:
            for topic_id in topic_ids:
                topic = get_object_or_404(Topic, pk=topic_id)
                topic.delete()
            messages.success(request, _("Topics deleted"))
            return HttpResponseRedirect(reverse('djangobb:index'))
        elif 'open_topics' in request.POST:
            for topic_id in topic_ids:
                open_close_topic(request, topic_id, 'o')
            messages.success(request, _("Topics opened"))
            return HttpResponseRedirect(reverse('djangobb:index'))
        elif 'close_topics' in request.POST:
            for topic_id in topic_ids:
                open_close_topic(request, topic_id, 'c')
            messages.success(request, _("Topics closed"))
            return HttpResponseRedirect(reverse('djangobb:index'))

        return render(request, 'djangobb_forum/moderate.html', {'forum': forum,
                'topics': topics,
                #'sticky_topics': forum.topics.filter(sticky=True),
                'posts': forum.posts.count(),
                })
    else:
        raise Http404


def search(request):
    # TODO: used forms in every search type

    def _render_search_form(form=None):
        return render(request, 'djangobb_forum/search_form.html', {'categories': Category.objects.all(),
                'form': form,
                })

    if not 'action' in request.GET:
        return _render_search_form(form=PostSearchForm())

    if request.GET.get("show_as") == "posts":
        show_as_posts = True
        template_name = 'djangobb_forum/search_posts.html'
    else:
        show_as_posts = False
        template_name = 'djangobb_forum/search_topics.html'

    context = {}

    # Create 'user viewable' pre-filtered topics/posts querysets
    viewable_category = Category.objects.all()
    topics = Topic.objects.all().order_by("-last_post__created")
    posts = Post.objects.all().order_by('-created')
    user = request.user
    if not user.is_superuser:
        user_groups = user.groups.all() or [] # need 'or []' for anonymous user otherwise: 'EmptyManager' object is not iterable 
        viewable_category = viewable_category.filter(Q(groups__in=user_groups) | Q(groups__isnull=True))

        topics = Topic.objects.filter(forum__category__in=viewable_category)
        posts = Post.objects.filter(topic__forum__category__in=viewable_category)

    base_url = None
    _generic_context = True

    action = request.GET['action']
    if action == 'show_24h':
        date = timezone.now() - timedelta(days=1)
        if show_as_posts:
            context["posts"] = posts.filter(Q(created__gte=date) | Q(updated__gte=date))
        else:
            context["topics"] = topics.filter(Q(last_post__created__gte=date) | Q(last_post__updated__gte=date))
        _generic_context = False
    elif action == 'show_new':
        if not user.is_authenticated():
            raise Http404("Search 'show_new' not available for anonymous user.")
        try:
            last_read = PostTracking.objects.get(user=user).last_read
        except PostTracking.DoesNotExist:
            last_read = None

        if last_read:
            if show_as_posts:
                context["posts"] = posts.filter(Q(created__gte=last_read) | Q(updated__gte=last_read))
            else:
                context["topics"] = topics.filter(Q(last_post__created__gte=last_read) | Q(last_post__updated__gte=last_read))
            _generic_context = False
        else:
            #searching more than forum_settings.SEARCH_PAGE_SIZE in this way - not good idea :]
            topics_id = [topic.id for topic in topics[:forum_settings.SEARCH_PAGE_SIZE] if forum_extras.has_unreads(topic, user)]
            topics = Topic.objects.filter(id__in=topics_id) # to create QuerySet

    elif action == 'show_unanswered':
        topics = topics.filter(post_count=1)
    elif action == 'show_subscriptions':
        topics = topics.filter(subscribers__id=user.id)
    elif action == 'show_user':
        # Show all posts from user or topics started by user
        if not user.is_authenticated():
            raise Http404("Search 'show_user' not available for anonymous user.")

        user_id = request.GET.get("user_id", user.id)
        try:
            user_id = int(user_id)
        except ValueError:
            raise SuspiciousOperation()

        if user_id != user.id:
            try:
                search_user = User.objects.get(id=user_id)
            except User.DoesNotExist:
                messages.error(request, _("Error: User unknown!"))
                return HttpResponseRedirect(request.path)
            messages.info(request, "Filter by user '%s'." % search_user.username)

        if show_as_posts:
            posts = posts.filter(user__id=user_id)
        else:
            # show as topic
            topics = topics.filter(posts__user__id=user_id).order_by("-last_post__created").distinct()

        base_url = "?action=show_user&user_id=%s&show_as=" % user_id
    elif action == 'search':
        form = PostSearchForm(request.GET)
        if not form.is_valid():
            return _render_search_form(form)

        keywords = form.cleaned_data['keywords']
        author = form.cleaned_data['author']
        forum = form.cleaned_data['forum']
        search_in = form.cleaned_data['search_in']
        sort_by = form.cleaned_data['sort_by']
        sort_dir = form.cleaned_data['sort_dir']

        query = SearchQuerySet().models(Post)

        if author:
            query = query.filter(author__username=author)

        if forum != u'0':
            query = query.filter(forum__id=forum)

        if keywords:
            if search_in == 'all':
                query = query.filter(SQ(topic=keywords) | SQ(text=keywords))
            elif search_in == 'message':
                query = query.filter(text=keywords)
            elif search_in == 'topic':
                query = query.filter(topic=keywords)

        order = {'0': 'created',
                 '1': 'author',
                 '2': 'topic',
                 '3': 'forum'}.get(sort_by, 'created')
        if sort_dir == 'DESC':
            order = '-' + order

        posts = query.order_by(order)

        if not show_as_posts:
            # TODO: We have here a problem to get a list of topics without double entries.

djangobb_forum/templates/djangobb_forum/add_topic.html
{% extends 'djangobb_forum/base.html' %}
{% load forum_extras %}
{% load i18n %}

{% block content %}
<div class="linkst">
	<div class="inbox">
		{% if forum %}
		<ul class="start"><li><a href="{% url 'djangobb:index' %}">{% trans "Root" %}</a> </li><li>&raquo; {% link forum %}</li></ul>
		{% else %}
			<ul><li><a href="{% url 'djangobb:index' %}">{% trans "Root" %}</a> </li><li>&raquo; {% link topic.forum %}</li><li>&raquo; {{ topic }}</li></ul>
		{% endif %}
		<div class="clearer"></div>
	</div>
</div>
{% include "djangobb_forum/includes/post_form.html" %}
{% endblock %}

djangobb_forum/templates/djangobb_forum/moderators.html
{% load forum_extras %}
{% load i18n %}
<em>({% trans "Moderated by" %}</em> 
	{% for moderator in moderators %}
		{% if forloop.last %}
			{{ moderator|profile_link }})
		{% else %}
			{{ moderator|profile_link }},
		{% endif %}
	{% endfor %}

djangobb_forum/templates/djangobb_forum/topic.html
{% extends 'djangobb_forum/base.html' %}
{% load forum_extras %}
{% load pagination_tags %}
{% load i18n %}

{% block title %} / {{ topic.forum.name }} / {{ topic.name }}{% endblock %}
{% block content %}
{% autopaginate posts forum_settings.TOPIC_PAGE_SIZE %}
<div class="linkst">
	<div class="inbox">
		<div class="pagelink conl">{% paginate %}</div>
		<ul>
			<li>
			<a href="{% url 'djangobb:index' %}">{% trans "Root" %} </a></li><li>&raquo; {% link topic.forum %} </li><li>&raquo; {{ topic.name }}
			<a href="{% url 'djangobb:forum_topic_feed' topic.id %}"><img src="{{ STATIC_URL }}djangobb_forum/img/feed-icon-small.png" alt="[RSS Feed]" title="[RSS Feed]" class="breadcrumb_rss" /></a>
			</li>
		</ul>
		<div class="clearer"></div>
	</div>
</div>

{% if poll %}
<div id="poll" class="block">
    <h2><span>{% trans "Poll" %}</span></h2>
    <div class="box">
        <div class="inbox"><p><strong>{{ poll.question }}</strong></p>
        {% if poll_form %}       
            <form action="." method="post">{% csrf_token %}
            {{ poll_form }}
            {% if poll.choice_count > 1 %}
            <p>
                {% blocktrans with count=poll.choice_count %}({{ count }} answers allows.){% endblocktrans %}
            </p>
            {% endif %}
            <input type="submit" name="{{ poll_form.FORM_NAME }}" value="{% trans "Vote" %}" />
            </form>
        {% else %}
            <ul>               
            {% for choice in poll.choices.all %}
                <li>
                    <div class="bar" style="width:{{ choice.percent|floatformat:0 }}%;" title="{{ choice.choice }}">&nbsp;</div>
                    {{ choice.votes }} vote{{ choice.votes|pluralize }} ({{ choice.percent|floatformat:1 }}%) for: {{ choice.choice }}
                </li>
            {% endfor %}
            </ul>
        {% endif %}
        </div>
    </div>
</div>
{% endif %}

{% for post in posts %}
	<div id="p{{ post.id }}" class="blockpost roweven firstpost">
		<a name="post-{{ post.id }}"></a>
		<h2><span><span class="conr">#{{ forloop.counter }}&nbsp;</span><a href="{{ post.get_absolute_url }}">{% forum_time post.created %}</a></span></h2>
		<div class="box">
			<div class="inbox">
				<div class="postleft">
					<dl>
						<dt><strong class="username">{{ post.user.username }}</strong></dt>
						<dd class="usertitle">
							{% if post.user.forum_profile.status %}
								<strong>{{ post.user.forum_profile.status }}</strong>
							{% else %}
								<strong>{{ post.user.forum_profile.group }}</strong>
							{% endif %}
						</dd>
						{% if forum_settings.AUTHORITY_SUPPORT %}
							<dd class="usertitle">
								{{ post.user|forum_authority }}
							</dd>
						{% endif %}
						<dd class="postavatar">
							{% if post.user.forum_profile.avatar and post.user.forum_profile.show_avatar %}
								<img src="{{ post.user.forum_profile.avatar.url }}" />
							{% else %}
								{% if forum_settings.GRAVATAR_SUPPORT %}
									<img src="{% gravatar post.user.email %}" />
								{% endif %}
							{% endif %}
						</dd>
						{% if post.user.forum_profile.location %}
							<dd>{% trans "From:" %} {{ post.user.forum_profile.location }}</dd>
						{% endif %}
						<dd>{% trans "Registered:" %} {{ post.user.date_joined|date:"Y-m-d" }}</dd>
						<dd>{% trans "Posts:" %} {{ post.user.forum_profile.post_count }}</dd>
						{% if moderator %}
							<dd>{% trans "IP:" %} {{ post.user_ip }}</dd>
						{% endif %}
						{% if forum_settings.REPUTATION_SUPPORT %}
								<dd><a href="{% url 'djangobb:reputation' post.user.username %}">{% trans "Reputation" %}</a>:
								{% if request.user != post.user %} {# TODO: and user.is_authenticated #}
									<a href="{% url 'djangobb:reputation' post.user.username %}?action=plus&amp;post_id={{ post.id }}"><img src="{{ STATIC_URL }}djangobb_forum/img/reputation/warn_add.gif" alt="+" /></a>&nbsp;&nbsp;<strong>{{ post.user.forum_profile.reply_total|default_if_none:"0" }}&nbsp;&nbsp;</strong><a href="{% url 'djangobb:reputation' post.user.username %}?action=minus&amp;post_id={{ post.id }}"><img src="{{ STATIC_URL }}djangobb_forum/img/reputation/warn_minus.gif" alt="-" /></a>
								{% else %}
									<strong>{{ post.user.forum_profile.reply_total|default_if_none:"0" }}</strong>
								{% endif %}
								</dd>
						{% endif %}
						<dd class="usercontacts"><a href="{% url 'djangobb:forum_profile' post.user.username %}">{% trans "Profile" %}</a>&nbsp;&nbsp;
						{% if post.user.forum_profile.privacy_permission == 0 %}
							<a href="mailto:{{ post.user.email }}">{% trans "E-mail" %}</a>&nbsp;&nbsp;
						{% else %}
							{% if post.user.forum_profile.privacy_permission == 1 %}
								<a href="{% url 'djangobb:misc' %}?mail_to={{ post.user.username }}">{% trans "Send e-mail" %}</a>&nbsp;&nbsp;
							{% endif %}
						{% endif %}
						{% if forum_settings.PM_SUPPORT %}
							{% if user.is_authenticated %}
								<a href="{% url 'messages_compose_to' post.user.username %}">{% trans "PM" %}</a>&nbsp;&nbsp;</dd>
							{% endif %}
						{% endif %}
				</dl>
			</div>
			<div class="postright">
				<h3>{{ post.topic.name }}</h3>
				<div class="postmsg">
					<p class="post_body_html">{{ post.body_html|safe }}</p>
					{% if not user.is_authenticated or user.forum_profile.show_signatures %}
						{% if post.user.forum_profile.signature_html %}
						<div class="postsignature">
							<br /><br/ >
							{{ post.user.forum_profile.signature_html|safe }}
						</div>
						{% endif %}
					{% endif %}
					{% if post.updated %}
						<p class="postedit"><em>{% trans "Edited" %} {{ post.updated_by.username }} ({% forum_time post.updated %})</em></p>
					{% endif %}
					{% with post.attachments.all as attachments %}
						{% if attachments %}
							{% for attach in attachments %}
								<p class="postedit"><em>{% trans "Attachments:" %} <br />{{ attach|attachment_link }}</em></p>
							{% endfor %}
						{% endif %}
					{% endwith %}
				</div>
			</div>
			<div class="clearer"></div>
			<div class="postfootleft">
				{% if post.user|online %}
					<p><strong>{% trans "Online" %}</strong></p>
				{% else %}
					<p>{% trans "Offline" %}</p>
				{% endif %}
			</div>
			<div class="postfootright">
				<ul>
					<li class="postreport"><a href="{% url 'djangobb:misc' %}?action=report&amp;post_id={{ post.id }}">{% trans "Report" %}</a> </li>
					{% if moderator or post|forum_equal_to:last_post %}
						{% if moderator or post.user|forum_equal_to:user %}
							<li class="postdelete">| <a onclick="return confirm('{% trans "Are you sure you want to delete this post?" %}')" href="{% url 'djangobb:delete_post' post.id %}">{% trans "Delete" %}</a> </li>
						{% endif %}
					{% endif %}
					{% if moderator or post|forum_posted_by:user %}
						<li class="postedit">| <a href="{% url 'djangobb:edit_post' post.id %}">{% trans "Edit" %}</a> </li>
					{% endif %}
					{% if user.is_authenticated %}
						<li class="postquote">| <a onclick="return copy_paste('p{{ post.id }}');" href="#reply" title="{% trans "Full quote or quote selected text form this post." %}">{% trans "Quote" %}</a></li>
					{% endif %}
				</ul>
			</div>
		</div>
	</div>
</div>
{% endfor %}
<div class="postlinksb">
	<div class="inbox">
		<div class="pagelink conl">{% paginate %}</div>
			<ul>
			    <li><a href="{% url 'djangobb:index' %}">{% trans "Root" %} </a></li>
			    <li>&raquo; {% link topic.forum %} </li>
			    <li>
			        &raquo; {{ topic }}<a href="{% url 'djangobb:forum_topic_feed' topic.id %}"><img src="{{ STATIC_URL }}djangobb_forum/img/feed-icon-small.png" alt="[RSS Feed]" title="[RSS Feed]" class="breadcrumb_rss" /></a>
			    </li>
            </ul>
		{% if user.is_authenticated %}
			{% if subscribed %}
				<a class="subscribelink clearb" href="{% url 'djangobb:forum_delete_subscription' topic.id %}?from_topic">{% trans "Unsubscribe" %}</a>
			{% else %}
				<a class="subscribelink clearb" href="{% url 'djangobb:forum_add_subscription' topic.id %}">{% trans "Subscribe" %}</a>
			{% endif %}
		{% endif %}
		<div class="clearer"></div>
	</div>
</div>

{% if reply_form %}
    {% with form=reply_form %}
        {% include "djangobb_forum/includes/post_form.html" %}
    {% endwith %}
{% endif %}

{% endblock content%}

{% block controls %}
<div class="conl">
	<form id="qjump" method="get" action="forum">
		<div><label>{% trans "Jump to " %}
		<br />
		<select name="id" id="forum_id" onchange="window.location=('{% url 'djangobb:index' %}'+this.options[this.selectedIndex].value)">
			{% for category in categories %}
				<optgroup label="{{ category }}">
					{% for forum in category.forums.all %}
						<option value="{{ forum.id }}">{{ forum }}</option>
					{% endfor %}
				</optgroup>
			{% endfor %}
		</select>
		<input type="button" onclick="window.location=('{% url 'djangobb:index' %}'+getElementById('forum_id').value)" value=" {% trans "Go" %} " accesskey="g" />
		</label></div>
	</form>
	<dl id="modcontrols"><dt><strong>{% trans "Moderator control" %}</strong></dt>
	{% if moderator %}
		<dd><a href="{% url 'djangobb:delete_posts' topic.id %}">{% trans "Delete multiple posts" %}</a></dd>
		<dd><a href="{% url 'djangobb:move_topic' %}?topic_id={{ topic.id }}">{% trans "Move topic" %}</a></dd>
		{% if topic.closed %}
			<dd><a href="{% url 'djangobb:open_close_topic' topic.id 'o' %}">{% trans "Open topic" %}</a></dd>
		{% else %}
			<dd><a href="{% url 'djangobb:open_close_topic' topic.id 'c' %}">{% trans "Close topic" %}</a></dd>
		{% endif %}
		{% if topic.sticky %}
			<dd><a href="{% url 'djangobb:stick_unstick_topic' topic.id 'u' %}">{% trans "Unstick topic" %}</a></dd></dl>
		{% else %}
			<dd><a href="{% url 'djangobb:stick_unstick_topic' topic.id 's' %}">{% trans "Stick topic" %}</a></dd></dl>
		{% endif %}
	{% endif %}
    </dl>
</div>
{% endblock %}

{% block lofi %}
{% if forum_settings.LOFI_SUPPORT %}
    <p class="lofi">
        <a href="{{ topic.get_absolute_url }}lofi/">Lo-Fi Version</a>
    </p>
{% endif %}
{% endblock %}